# Generated by Django 5.1.1 on 2024-10-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_app", "0002_category_alter_product_id_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category_name",
        ),
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.AddField(
            model_name="category",
            name="category_id",
            field=models.BigAutoField(primary_key=True),
            preserve_default=False,
        ),
    ]
