# Generated by Django 5.1.1 on 2024-10-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_app", "0003_rename_name_category_category_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_id",
        ),
        migrations.AddField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
